/* This file generated by mkprj.sh */
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>

#define pipe_rx	argv[1]
#define pipe_tx	argv[2]
#define MAX_BUF	100

int main(int argc, char** argv, char** env)
{
	int fd_rx, fd_tx, fifo_rx, fifo_tx;
	char buf_rx[MAX_BUF], buf_tx[MAX_BUF];
	pid_t pid_rx, pid_tx;
	
	if(argc < 2) {
		puts("usage:\tpipe_chat pipein pipeout - one terminal");
		puts("      \tpipe_chat pipeout pipein - two teminal");
		return 1;
	}
	if(access(pipe_rx, F_OK == -1)) fifo_rx = mkfifo(pipe_rx, 0666);
	if(access(pipe_tx, F_OK == -1)) fifo_tx = mkfifo(pipe_tx, 0666);
	

	switch(pid_rx = fork()) {
	case -1:
		perror("fork rx");
		exit(1);
	case 0:
		if((fd_rx = open(pipe_rx, O_RDONLY)) < 0) {
			perror("fopen pipe_rx");
			exit(EXIT_FAILURE);
		}
		printf("Type your message:\n");

		buf_rx[0] = 0;

		while(1) {
			int n = read(fd_rx, buf_rx, MAX_BUF);
			if (n <= 0) break;
			buf_rx[n] = 0;
			printf("received >> %s\n", buf_rx);
		}
		close(fd_rx);
	}

	switch(pid_tx = fork()) {
		case -1:
			perror("fork tx");
			exit(EXIT_FAILURE);
		case 0:
			if((fd_tx = open(pipe_tx, O_WRONLY)) < 0) {
				perror("fopen pipe_tx");
				exit(EXIT_FAILURE);
			}
			buf_tx[0] = 0;
			while(fgets(buf_tx, MAX_BUF, stdin) != NULL )
				if(write(fd_tx, buf_tx , strlen(buf_tx)) <= 0) break;
			close(fd_tx);
	}

	if(waitpid(pid_rx, &fifo_rx, 0) != pid_rx || waitpid(pid_tx, &fifo_tx, 0) != pid_tx)
		perror("shit happened during the wait pid");
	return 0;
}
