/* This file generated by mkprj.sh */
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include <pthread.h>




void my_signal_handler(int sig)
{
	printf("sig = %d", sig);
	switch(sig) {
		case SIGINT:
			puts("Exiting...");
			exit(0);
		default:
			break;
	}
}

void* thread_writers(void* arg)
{

}



void* thread_readers(void* arg)
{

}


int main(int argc, char** argv, char** env)
{
	int wrs, rds, max;
	if(argc < 3) {
		printf("usage:\t%s writer readers max\n", argv[0]);
		puts("writers - количество писателей");
		puts("readers - количество читателей");
		puts("max - максимальное количество элементов в контейнере");
		return 0;

	}
	wrs = atoi(argv[1]);
	rds = atoi(argv[2]);
	max = atoi(argv[3]);

	signal(SIGINT, my_signal_handler);

	if(pthread_create(&thread[i], NULL, &my_thread_func, &param_list[i]) != 0) {
		perror("pthread_create");
		return -1;
	}


	while(1) {
		sleep(1);
	}

	return 0;
}
