/* This file generated by mkprj.sh */
#include <stdio.h>
#include <stdlib.h>
#include <dirent.h>
#include <string.h>
#include <malloc.h>

#define	MAX_BUF	256

int main(int argc, char** argv, char** env)
{
	//int ;
	DIR *proc_dir, *proc_dir1;
	int pid, tpid, multi = 0;
	char *buf;
	struct dirent *dp, *dp1;
	if(argc < 2) {
		printf("usage:\t%s [process]\n", argv[0]);
		puts("If process = \"all\", then print all processes.");
		return 0;
	}
	if(strcmp(argv[1], "all\0") == 0){
		puts("Print all processes.");
		multi = 1;
		proc_dir1 = opendir("/proc");
	} 
	do {
		if(multi == 1){
			dp1 = readdir(proc_dir1);
			pid = strtol(dp1->d_name, NULL, 10);
			if(pid == NULL) {
				puts("pid = 0, exiting.");
				closedir(proc_dir1);
				break;
			}
		} else {
			pid = atoi(argv[1]);
		}
		buf = calloc(sizeof(buf), MAX_BUF);
		if(buf == NULL) {
			puts("Error memory allocate.");
			return -1;
		}
		sprintf(buf, "/proc/%d/task", pid);
		proc_dir = opendir(buf);
		free(buf);
		if(proc_dir == NULL) {
			printf("Error process %d \n", pid);
			return -1;
		}
		dp = readdir(proc_dir);
		while(dp) {
			tpid = strtol(dp->d_name, NULL, 10);
			if(tpid > 0) {
				if (tpid==pid)	//	(errno != ERANGE)
					printf("%d - main task\n", pid);
				else
					printf( "\t|-%d\n", tpid);
			}
			dp = readdir(proc_dir);
		}
		closedir(proc_dir);
	}while(multi);
	return 0;

}
