/* This file generated by mkprj.sh */
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <poll.h>


#define pipe_rx	argv[1]
#define pipe_tx	argv[2]
#define MAX_BUF	100


int fd_rx, fd_tx;


void my_signal_handler(int sig)
{
	switch(sig) {
		case SIGINT:
			puts("Exiting...");
			close(fd_rx);
			close(fd_tx);
			exit(0);
		default:
			break;
	}
}

int main(int argc, char** argv, char** env)
{
	char buf_rx[MAX_BUF], buf_tx[MAX_BUF];
	int n;
	int retval;
	struct pollfd my_fds[2] = {{STDIN_FILENO,POLLIN,0}, {0,POLLIN,0}};
	
	if(argc < 2) {
		puts("usage:\tpoll pipein pipeout - one terminal");
		puts("      \tpoll pipeout pipein - two teminal");
		return 1;
	}

	signal(SIGINT, my_signal_handler);

	if(access(pipe_rx, F_OK) != 0) {
		puts("No pipe_rx found. Create it.");
		retval = mkfifo(pipe_rx, 0666);
		if(retval != 0) {
			puts("Errorr mkfifo pipe_rx!");
			exit(-1);
		}
	}

	if(access(pipe_tx, F_OK) != 0) {
		puts("No pipe_tx found. Create it.");
		retval = mkfifo(pipe_tx, 0666);
		if(retval != 0) {
			puts("Errorr mkfifo pipe_tx!");
			exit(-1);
		}
	}	

	if((fd_rx = open(pipe_rx, O_RDWR)) < 0) {
		puts("Error open pipe_rx");
		perror("fopen pipe_rx");
		fflush(STDIN_FILENO);
		exit(EXIT_FAILURE);
	}
//	puts("open(pipe_tx, O_RDONLY)");
	if((fd_tx = open(pipe_tx, O_RDWR)) < 0) {
		puts("Error open pipe_tx");
		perror("fopen pipe_tx");
		exit(EXIT_FAILURE);
	}
	
	my_fds[1].fd = fd_rx;
	puts("Press CTRL+C to exit. Type your message:");


	buf_rx[0] = 0;

	while(1) {
		retval = poll((struct pollfd*)&my_fds, 2, 1);
		switch(retval) {
			case 0:// timeout
				continue;
			break;
			case -1:// error
				exit(-1);
			default:
				if(my_fds[0].revents & POLLIN) {// STD_IN
					if(fgets(buf_tx, MAX_BUF, stdin) != NULL) {
						if(write(fd_tx, buf_tx , strlen(buf_tx)) <= 0) break;
					}
				}
				if(my_fds[1].revents & POLLIN) {// PIPE RX
					n = read(fd_rx, buf_rx, MAX_BUF);
					if (n <= 0) break;
					buf_rx[n] = 0;
					printf("received >> %s", buf_rx);
				}
			break;
				
		}
	}	
	close(fd_rx);
	close(fd_tx);
	return 0;
}
