/* This file generated by mkprj.sh */
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>


#define pipe_rx	argv[1]
#define pipe_tx	argv[2]
#define MAX_BUF	100

void my_signal_handler(int sig)
{
	switch(sig) {
		case SIGINT:
			puts("Exiting...");
			exit(0);
		default:
			break;
	}
}

int main(int argc, char** argv, char** env)
{
	int fd_rx, fd_tx;
	char buf_rx[MAX_BUF], buf_tx[MAX_BUF];

	struct timeval timeout;
	fd_set rfds, wfds;
	int retval;

	
	
	if(argc < 2) {
		puts("usage:\tselect pipein pipeout - one terminal");
		puts("      \tselect pipeout pipein - two teminal");
		return 1;
	}

	signal(SIGINT, my_signal_handler);

	if(access(pipe_rx, F_OK) != 0) {
		puts("No pipe_rx found. Create it.");
		retval = mkfifo(pipe_rx, 0666);
		if(retval != 0) {
			puts("Errorr mkfifo pipe_rx!");
			exit(-1);
		}
	}

	if(access(pipe_tx, F_OK) != 0) {
		puts("No pipe_tx found. Create it.");
		retval = mkfifo(pipe_tx, 0666);
		if(retval != 0) {
			puts("Errorr mkfifo pipe_tx!");
			exit(-1);
		}
	}	

	timeout.tv_sec = 5;
	timeout.tv_usec = 0;

	if((fd_rx = open(pipe_rx, O_RDWR)) < 0) {
		puts("Error open pipe_rx");
		perror("fopen pipe_rx");
		fflush(STDIN_FILENO);
		exit(EXIT_FAILURE);
	}
	puts("open(pipe_tx, O_RDONLY)");
	if((fd_tx = open(pipe_tx, O_RDWR)) < 0) {
		puts("Error open pipe_tx");
		perror("fopen pipe_tx");
		exit(EXIT_FAILURE);
	}

	puts("Press CTRL+C to exit. Type your message:");


	buf_rx[0] = 0;

	while(1) {
		FD_ZERO(&rfds);
		FD_SET(fd_rx, &rfds);
		FD_SET(STDIN_FILENO, &rfds);

		FD_ZERO(&wfds);
		FD_SET(fd_tx, &rfds);
		retval = select(10, &rfds, &wfds, NULL, &timeout);
		if (FD_ISSET(fd_rx, &rfds)) {
			int n = read(fd_rx, buf_rx, MAX_BUF);
			if (n <= 0) break;
			buf_rx[n] = 0;
			printf("received >> %s", buf_rx);
		}

		if (FD_ISSET(fd_tx, &wfds)) {
// нет необходимости
		}

		if (FD_ISSET(STDIN_FILENO, &rfds)) {
			if(fgets(buf_tx, MAX_BUF, stdin) != NULL)
				if(write(fd_tx, buf_tx , strlen(buf_tx)) <= 0) break;
		}
	}
		
	close(fd_rx);
	close(fd_tx);
	return 0;
}
