/* This file generated by mkprj.sh */
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <fcntl.h>


#define pipe_rx	argv[1]
#define pipe_tx	argv[2]
#define MAX_BUF	100

int main(int argc, char** argv, char** env)
{
	int fd_rx, fd_tx;
	char buf_rx[MAX_BUF], buf_tx[MAX_BUF];

	struct timeval timeout;
	fd_set rfds, wfds;
	int retval;

	
	
	if(argc < 2) {
		puts("usage:\tpipe_chat pipein pipeout - one terminal");
		puts("      \tpipe_chat pipeout pipein - two teminal");
		return 1;
	}
	if(access(pipe_rx, F_OK == -1)) {
		retval = mkfifo(pipe_rx, 0666);
		if(retval != 0) exit(-1);
	}
	if(access(pipe_tx, F_OK == -1)) {
		retval = mkfifo(pipe_tx, 0666);
		if(retval != 0) exit(-1);
	}	

	timeout.tv_sec = 5;
	timeout.tv_usec = 0;

	if((fd_rx = open(pipe_rx, O_RDONLY)) < 0) {
		perror("fopen pipe_rx");
		exit(EXIT_FAILURE);
	}
	if((fd_tx = open(pipe_tx, O_WRONLY)) < 0) {
		perror("fopen pipe_tx");
		exit(EXIT_FAILURE);
	}
	printf("Type your message:\n");


	buf_rx[0] = 0;

	while(1) {
		FD_ZERO(&rfds);
		FD_SET(fd_rx, &rfds);
		FD_SET(STDIN_FILENO, &rfds);

		FD_ZERO(&wfds);
		FD_SET(fd_tx, &rfds);
		retval = select(10, &rfds, &wfds, NULL, &timeout);
		if (FD_ISSET(fd_rx, &rfds)) {
			int n = read(fd_rx, buf_rx, MAX_BUF);
			if (n <= 0) break;
			buf_rx[n] = 0;
			printf("received >> %s\n", buf_rx);
		}

		if (FD_ISSET(fd_tx, &wfds)) {
// нет необходимости
		}

		if (FD_ISSET(STDIN_FILENO, &rfds)) {
			if(fgets(buf_tx, MAX_BUF, stdin) != NULL)
				if(write(fd_tx, buf_tx , strlen(buf_tx)) <= 0) break;
		}
	}
		
	close(fd_rx);
	close(fd_tx);
	return 0;
}
