/* This file generated by mkprj.sh */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/socket.h>
#include <string.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/wait.h>

int main(int argc, char** argv, char** env)
{
	int sock;
	struct sockaddr_in inaddr, outaddr, fromaddr;
	if(argc > 1) {
		printf("usage:\t%s\n", argv[0]);
		return 0;
	}
	sock = socket(AF_INET, SOCK_RAW, 0);
	if(sock < 0) {
		perror("socket");
		exit(1);
	}

	memset(&inaddr, 0, sizeof(inaddr));
	inaddr.sin_family = AF_INET;
	inaddr.sin_port = 80;
	inaddr.sin_addr.s_addr = htonl((in_addr_t) INADDR_LOOPBACK);
	

	memset(&outaddr, 0, sizeof(outaddr));
	outaddr.sin_family = AF_INET;
	outaddr.sin_port = 80;
	outaddr.sin_addr.s_addr = htonl((in_addr_t) INADDR_LOOPBACK);

	return 0;
}
