/* This file generated by mkprj.sh */
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>

char text[] = "1233321123123";

int main(int argc, char** argv, char** env)
{
	int remoteport, localport;
	int sock;
	struct sockaddr_in addr;
	if(argc < 2) {
		printf("usage:\t%s localport remoteport\n", argv[0]);
		return 0;
	}
	localport = atoi(argv[1]);
	remoteport = atoi(argv[2]);

	sock = socket(AF_INET, SOCK_DGRAM, 0);
	if(sock < 0) {
		perror("socket");
		exit(1);
	}

	addr.sin_family = AF_INET;
	addr.sin_port = htons(remoteport);
	addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
	connect(sock, (struct sockaddr *)&addr, sizeof(addr));
	send(sock, text, sizeof(text), 0);
	




	return 0;
}
