/* This file generated by mkprj.sh */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/socket.h>
#include <string.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/wait.h>

#define MAX_BUF	100

int main(int argc, char** argv, char** env)
{
	int remoteport, localport;
	int sock;
	struct sockaddr_in inaddr, outaddr, fromaddr;
	pid_t pid_rx, pid_tx;
	char buf_rx[MAX_BUF], buf_tx[MAX_BUF];
	if(argc < 2) {
		puts("usage:\tudp_echo localport remoteport - one terminal");
		puts("      \tudp_echo remoteport localport - two teminal");
		return 0;
	}
	localport = atoi(argv[1]);
	remoteport = atoi(argv[2]);
	if(localport > 65000) {
		perror(argv[1]);
		exit(1);
	}

	if(remoteport > 65000) {
		perror(argv[2]);
		exit(1);
	}

	sock = socket(AF_INET, SOCK_DGRAM, 0);
	if(sock < 0) {
		perror("socket");
		exit(1);
	}

	memset(&inaddr, 0, sizeof(inaddr));
	inaddr.sin_family = AF_INET;
	inaddr.sin_port = htons(localport);
	inaddr.sin_addr.s_addr = htonl((in_addr_t) INADDR_LOOPBACK);
	

	memset(&outaddr, 0, sizeof(outaddr));
	outaddr.sin_family = AF_INET;
	outaddr.sin_port = htons(remoteport);
	outaddr.sin_addr.s_addr = htonl((in_addr_t) INADDR_LOOPBACK);

	switch(pid_rx = fork()) {
	case -1:
		perror("fork rx");
		exit(EXIT_FAILURE);
	case 0:
		printf("\nbind to inaddr....");
		while( bind(sock, (struct sockaddr*)&inaddr, sizeof(inaddr)) < 0) {
			perror("bind inaddr");
		}
		puts("success!");


		socklen_t ln = sizeof(fromaddr);
		buf_rx[0] = 0;
		printf("Type your message:\n");

		while(1) {
			int n = recvfrom(sock, buf_rx, MAX_BUF, 0, (struct sockaddr*)&fromaddr, &ln);
			if (n <= 0) break;
			buf_rx[n] = 0;
			if(fromaddr.sin_port == ntohs(remoteport))
				printf("received >> %s", buf_rx);
		}
	}

	switch(pid_tx = fork()) {
		case -1:
			perror("fork tx");
			exit(EXIT_FAILURE);
		case 0:
//			connect(sock, (struct sockaddr *)&outaddr, sizeof(outaddr));
			buf_tx[0] = 0;
			while(fgets(buf_tx, MAX_BUF, stdin) != NULL ) {
				int n = sendto(sock, buf_tx, MAX_BUF, 0, (struct sockaddr*)&outaddr, sizeof(struct sockaddr_in));
				if(n <= 0) break;
			}
	}

	if(waitpid(pid_rx, &sock, 0) != pid_rx || waitpid(pid_tx, &sock, 0) != pid_tx )
		perror("shit happened during the wait pid");
	close(sock);

	return 0;
}
